# Generated by Django 5.0.4 on 2024-04-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_progress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicprogress',
            name='text',
        ),
    ]
