# Generated by Django 5.0.4 on 2024-04-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_progress', '0002_userprogress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='topic',
        ),
    ]
