# Generated by Django 5.0.4 on 2024-05-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_progress', '0003_remove_userprogress_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
